### ISSUE TITLE
Push css to Postmatic

### ISSUE THREAD

**Issue by Vernal** [postmatic/elevated-comments#15]
http://docs.gopostmatic.com/article/191-prompt-html-email-print-styles-action

**Comment by cyberhobo** [comment]
@Vernal that commit should put the same styles used on the web into Postmatic emails, try branch postmatic-css. If you need different CSS for the email version, put it in a separate file and we'll use that instead.

**Comment by Vernal** [comment]
Works perfect out of the box, homie. Nice going.

On April 26, 2016 at 9:16:58 AM, Dylan Kuhn (notifications@github.com) wrote:

@Vernal that commit should put the same styles used on the web into Postmatic emails, try branch postmatic-css. If you need different CSS for the email version, put it in a separate file and we'll use that instead.
