### ISSUE TITLE
Switch to using wp_insert_comment

### ISSUE THREAD

**Issue by Vernal** [postmatic/elevated-comments#20]
Currently EC uses comment_post, which limits the fun we can have between it and Postmatic. Switch to wp_insert_comment for maximum carnage.

**Comment by filkaris** [comment]
See #21

**Comment by Vernal** [comment]
Did you do thorough testing on this? Need help with that?

**Comment by filkaris** [comment]
I just did a couple of comments to make sure it works, and that it works in tandem with postmatic. The parameter it uses (comment id) is the same in both hooks, and they are executed almost at the same time, so I don't believe a lot of testing is needed.

**Comment by Vernal** [comment]
Works for me as well.
