### ISSUE TITLE
not getting metadata from iq.gopostmatic

### ISSUE THREAD

**Issue by Vernal** [postmatic/elevated-comments#22]
I can't discern why. Using iq.gopostmatic I don't get any commentmeta. Using api.commentiq I do.

**Comment by ronalfy** [comment]
I'll make this priority over #11

I'll try to figure this out this evening.

**Comment by Vernal** [comment]
Thanks man. Confirmed the server is up and everything. :(

On April 27, 2016 at 4:35:45 PM, Ronald Huereca (notifications@github.com) wrote:

I'll make this priority over #11

I'll try to figure this out this evening.

**Comment by ronalfy** [comment]
No worries. Still might be a DNS issue or something since we just recently put it up, but I think it's been long enough.
