### ISSUE TITLE
Bug: Elevated Comments Causes Captions to Not Work in Post Content

### ISSUE THREAD

**Issue by ronalfy** [postmatic/elevated-comments#31]
Don't have too many details ATM, but having Elevated Comments disables captions in the post content.

**Comment by Vernal** [comment]
Ok i’ll look into it today.

On May 16, 2016 at 1:08:08 AM, Ronald Huereca (notifications@github.com) wrote:

Don't have too many details ATM, but having Elevated Comments disables captions in the post content.

**Comment by ronalfy** [comment]
@Vernal please take a look at the PR when you get a chance.
