### ISSUE TITLE
Look into hr removal in genesis

### ISSUE THREAD

**Issue by Vernal** [postmatic/elevated-comments#33]
From a user:

> I found an odd little bug. I am using Genesis child theme from StudioPress. When I have the Elevated Comments activated, for some reason anywhere that I have used

Want to investigate?

**Comment by ronalfy** [comment]
Do you have a copy of the Genesis theme you can share?

**Comment by ronalfy** [comment]
Ping me when you're online. The main issue is the regex parsing. I think we need to find an alternate solution for inserting Elevated Comments in the content.

**Comment by ronalfy** [comment]
Nevermind. I redid how the html is parsed. Nothing should be stripped out now.
